import React, { useState } from 'react';
import { Sparkles, X, Bot, Send, Loader2, CheckCircle2, Factory, ChevronRight } from 'lucide-react';

interface AIAssistantModalProps {
  isOpen: boolean;
  onClose: () => void;
  onApplySpecToQuote?: (category: string, strength: string, flavor: string) => void;
}

export const AIAssistantModal: React.FC<AIAssistantModalProps> = ({
  isOpen,
  onClose,
  onApplySpecToQuote
}) => {
  const [brandConcept, setBrandConcept] = useState('');
  const [productCategory, setProductCategory] = useState<'nicotine' | 'nootropic' | 'caffeine'>('nicotine');
  const [targetAudience, setTargetAudience] = useState('');
  const [questions, setQuestions] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);

  if (!isOpen) return null;

  const handleConsult = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const res = await fetch('/api/ai-spec-consultant', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          brandConcept,
          productCategory,
          targetAudience,
          questions
        })
      });
      const data = await res.json();
      setResult(data);
    } catch (err) {
      console.error('AI Spec error:', err);
      setResult({
        recommendation: "Based on your concept, we suggest a 6mg Nicotine or 80mg Caffeine pouch in a 0.45g slim pouch format with Spearmint Freeze flavor, 20-pouch puck, and 10,000-can pilot MOQ at our Phoenix facility.",
        estimatedTurnaround: "5-7 Days Samples, 2-3 Weeks Production",
        regulatoryNote: "All products manufactured under cGMP and FDA registered facility guidelines."
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/75 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl max-w-2xl w-full border border-slate-200 shadow-2xl overflow-hidden max-h-[90vh] flex flex-col">
        
        {/* Modal Header */}
        <div className="bg-slate-900 text-white p-6 flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-blue-950 text-blue-400 rounded-full border border-blue-800">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-xl font-extrabold text-white">AI Formulation & Pouch Spec Advisor</h3>
              <p className="text-xs text-slate-400">Phoenix Pouch Co. Automated OEM Technical Assistant</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-full text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1">
          {result ? (
            <div className="space-y-6">
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-2xl flex items-start gap-3">
                <Bot className="w-6 h-6 text-blue-700 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-slate-900 text-sm">Formulation Recommendation</h4>
                  <p className="text-xs text-slate-600 mt-0.5">Custom analysis generated by Phoenix Pouch R&D advisor</p>
                </div>
              </div>

              <div className="prose prose-sm max-w-none text-slate-800 bg-slate-50 p-5 rounded-2xl border border-slate-200 whitespace-pre-wrap leading-relaxed">
                {result.recommendation}
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                <div className="p-3 bg-slate-100 rounded-xl border border-slate-200">
                  <div className="font-bold text-slate-700">Estimated Production Time:</div>
                  <div className="text-slate-900 font-mono mt-0.5">{result.estimatedTurnaround}</div>
                </div>
                <div className="p-3 bg-slate-100 rounded-xl border border-slate-200">
                  <div className="font-bold text-slate-700">Compliance Standard:</div>
                  <div className="text-slate-900 font-mono mt-0.5">cGMP & FDA Registered Facility</div>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-3 pt-2">
                <button
                  onClick={() => {
                    if (onApplySpecToQuote) {
                      onApplySpecToQuote(
                        productCategory,
                        productCategory === 'nicotine' ? '6mg' : '80mg',
                        'Spearmint Freeze'
                      );
                    }
                    onClose();
                  }}
                  className="flex-1 py-3.5 px-6 bg-blue-700 hover:bg-blue-800 text-white font-bold text-sm rounded-full flex items-center justify-center gap-2 cursor-pointer shadow-lg shadow-blue-200/50"
                >
                  <span>Use This Spec & Request Official Quote</span>
                  <ChevronRight className="w-4 h-4" />
                </button>
                <button
                  onClick={() => setResult(null)}
                  className="py-3.5 px-6 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-sm rounded-full transition-colors cursor-pointer"
                >
                  Ask Another Question
                </button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleConsult} className="space-y-4">
              <p className="text-slate-600 text-sm">
                Describe your brand idea, target market, or technical questions below. Our AI engineer will generate optimized pouch specifications, flavor pairings, and MOQ recommendations tailored for our Phoenix plant.
              </p>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Select Product Line</label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { id: 'nicotine', name: 'Nicotine' },
                    { id: 'nootropic', name: 'Nootropic' },
                    { id: 'caffeine', name: 'Caffeine' }
                  ].map((cat) => (
                    <button
                      key={cat.id}
                      type="button"
                      onClick={() => setProductCategory(cat.id as any)}
                      className={`py-2 px-3 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
                        productCategory === cat.id
                          ? 'border-blue-700 bg-blue-50 text-blue-700 font-extrabold'
                          : 'border-slate-200 text-slate-700 hover:bg-slate-50'
                      }`}
                    >
                      {cat.name}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Brand Name / Concept Idea</label>
                <input
                  type="text"
                  value={brandConcept}
                  onChange={(e) => setBrandConcept(e.target.value)}
                  placeholder="e.g. ZenPouch - Premium Organic Mint Nicotine Pouch for Executive Wellness"
                  className="w-full px-4 py-2 border border-slate-300 rounded-xl text-sm focus:ring-2 focus:ring-blue-700 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Target Consumer / Demographic</label>
                <input
                  type="text"
                  value={targetAudience}
                  onChange={(e) => setTargetAudience(e.target.value)}
                  placeholder="e.g. US 21+ adult consumers looking for tobacco-free clean mint pouches"
                  className="w-full px-4 py-2 border border-slate-300 rounded-xl text-sm focus:ring-2 focus:ring-blue-700 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Specific Formulation Questions</label>
                <textarea
                  rows={3}
                  value={questions}
                  onChange={(e) => setQuestions(e.target.value)}
                  placeholder="e.g. What is the best moisture percentage for long shelf life? Can we add L-Theanine with caffeine?"
                  className="w-full px-4 py-2 border border-slate-300 rounded-xl text-sm focus:ring-2 focus:ring-blue-700 outline-none"
                />
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-4 px-6 bg-blue-700 hover:bg-blue-800 text-white font-extrabold text-sm rounded-full shadow-lg shadow-blue-200/50 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-70 transition-all"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Analyzing Specs & Formulations...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    <span>Generate AI Formulation Recommendation</span>
                  </>
                )}
              </button>
            </form>
          )}
        </div>

      </div>
    </div>
  );
};
